### ISSUE TITLE
Any way to know which key failed in JSON deserialization?

### ISSUE THREAD

**Issue by mergesort** [lyft/mapper#55] opened 2016-05-29 03:05 UTC
Hi there!

I am really loving Mapper, it allows the decoupled structure I've wanted from a JSON parser, but haven't been able to find elsewhere.

I've setup a relatively complicated set of models, where 1 model is dependent on 4 or 5 other models, and those models have their own dependencies inside as well. A simple version of these models may look something like this:

`Feed` (Consists of):
-- `Header`
  ---- `title`
  ---- `subtitle`
  ---- `date`

-- `Footer`
  ---- `Image`
    ------ `URL`
  ---- `title`
  ---- `subtitle`

When parsing the main model (`Feed`), at some point, one of those parsings fails (either in `Header`, `Footer`, or `Image`), and I'm having a difficult time figuring out which one is the one ultimately causing the JSON parsing to throw.

I've read through the readme a few times, read through the issues, and gone through the source code but still haven't been able to figure out if there's an easy way, other than commenting out all the models that don't work, and adding them back in one by one, to figure out which model is causing the parser to throw?

If there's any other information that may be helpful, please let me know. Thanks a lot!

**Comment by keith** [comment] 2016-05-29 06:18
Thanks for the kind words! Glad you like it!

I'm trying to follow your models here, but I think the custom `MapperError` cases could help you out (sorry I haven't updated the readme for these). As of 2.1.0 and https://github.com/lyft/mapper/pull/48 you'll get one of [these](https://github.com/lyft/mapper/blob/2.1.0/Sources/MapperError.swift#L17-L18) error cases (in most instances) when something fails. I'm just realizing now that that may not be as useful for nested objects as you would like, but in theory if the `title` property of `Header` throws because it doesn't exist in the JSON you should get that error populated up. In this case you would get a `MissingFieldError` where the `field` string was `title`.

The fact that the field is populated with that is probably only useful for debugging, but I'd be interested to hear what you'd want to use it for if you did want to take that into account at runtime.

Let me know if this makes sense / actually solves your problem!

**Comment by mergesort** [comment] 2016-05-29 14:52
I do only need it for debugging, didn't really have any thoughts on how to handle it during runtime. I think throwing is the right action.

I may not be understanding correctly, but where should I see the error bubbling up? 

I'm doing something like this:
do {
        let JSON = try NSJSONSerialization.JSONObjectWithData(data, options: NSJSONReadingOptions.init(rawValue: 0))
            if let JSON = JSON as? [ String : AnyObject ] {
                let issue = Issue.from(JSON)
                // Issue is nil, and failed to serialize correctly on one of my models, but don't know where
            }
} catch (let error): {
     // Be a good programmer and handle stuff here I guess
}

I also tried `try Issue.from(JSON)`, but realized it's not a throwing initializer, so it wouldn't go into the catch.

Maybe I'm missing something simple?

**Comment by keith** [comment] 2016-05-29 22:48
Ah right. So the issue here is that the `.from` function is a part of a [protocol extension](https://github.com/lyft/mapper/blob/master/Sources/Mappable.swift#L37-L38) that's just there for convenience so you can avoid the exception handling dance if you'd like.

In order to get the exception to bubble up here you'll need to use the `init(map: Mapper) throws` function that you defined in your models. Unfortunately we haven't come up with a better way to use this than calling it directly ([details](https://github.com/lyft/mapper/pull/17)).

So if you change: 

```swift
let issue = Issue.from(JSON)
```

to

```swift
let issue = try Issue(map: Mapper(JSON: JSON))
```

You should get your exceptions as you'd expect! If you can think of a nicer way to handle this flow please let us know. In our codebase we exclusively use `.from` so we haven't spent too much time thinking about this. As you can see in the linked PR I would be fine with a `.fromThrowable` type function, as long as we could find a nicer name (since we can't have 2 `.from` functions which only differ based on throwing).

**Comment by mergesort** [comment] 2016-05-30 04:02
Ah, that makes sense! Now I'm seeing my errors propagate, and it's much easier to debug. 😄

My gut says to say `throwableFrom` or `throwingFrom`, over `fromThrowable`. If that's not an option, how about `failableFrom` (to be technically correct) or `tryFrom` (to be explicit)? I can probably throw out at least a few more if none of those are worthy. 😉

**Comment by keith** [comment] 2016-05-30 18:42
After using the initializer directly, do you feel like a convenience function is necessary? I was more excited about adding one when I thought that meant we could make `Mapper`'s initializer `internal` but unfortunately we'll still have to keep it `public` in case you want to call it from a different initializer (since you have to call another initializer). Like:

```swift
init(someOtherInitializer: Something) {
    self.init(map: Mapper(JSON: ¯\_(ツ)_/¯)
}
```

**Comment by mergesort** [comment] 2016-05-30 19:42
Necessary? No... But that's not the point of a convenience. 😄

```MyStruct(map: Mapper(JSON: JSON))``` feels a bit verbose, and a bit like an incantation. I would say that using `from` (or some variation of the name) feels semantically more in-line with the rest of the API.

**Comment by keith** [comment] 2016-05-30 22:23
Yea definitely. I'll think on these names and try to add something soon. In the meantime I'm glad we got this figured out!

**Comment by ConorBrady** [comment] 2016-05-31 12:31
How about some environment variable that logs errors?

**Comment by keith** [comment] 2016-05-31 16:40
I think in many cases that would become extremely noisy. Especially if you're using `optionalFrom` in a lot of places. I think for debugging you'd be much better off handling the cases you're worried about and digging into them.

**Comment by keith** [comment] 2016-07-19 17:39
I'm closing this one for now, feel free to reopen a new issue if we have more to do here!

**Closed by keith** 2016-07-19 17:39 UTC

**Comment by RamblinWreck77** [comment] 2017-06-15 13:57
Just ran in to this. 

the fact that .from doesn't have a way to handle errors is pretty frustrating. It'd be really nice to have some kind of 
`#if(DEBUG)
print("\n🔥 Mapper failed when trying to do: \(thingIwasTrying.Part#) because \(CustomErrorClass)")
#endif`

RxSwift does this for several types of errors and it's pretty awesome to get colorful/meaningful warnings when something went wrong. 

Meanwhile @keith , your suggestion of a do/catch with 

`let issue = try Issue(map: Mapper(JSON: JSON))`

throws a 

`Error: The operation couldn’t be completed. (Mapper.MapperError error 0.)`

which still isn't particularly helpful. Is there a better way to get more information about where the error is occurring? The problem is in very large JSON objects it becomes a nightmare to debug, and I feel like there should be a better way than looking at diffs on git to find it. The data is clearly there, it's just a matter of getting at it.

**Comment by keith** [comment] 2017-06-15 15:58
When you catch the `MapperError` here, it should have some detailed information about why it failed. I can look in to making that description nicer though.

You can see the possible options [here](https://github.com/lyft/mapper/blob/master/Sources/MapperError.swift).
